name: Daily Email
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node scripts/send-email.js
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          SUPABASE_URL: https://qaocbodrflsaerxntfui.supabase.co
          SUPABASE_KEY: sb_publishable_eIeO9MihyuQDuNHy60Ubrw_8ZuSKPFU
